# Generated by Django 3.1.1 on 2020-10-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaapp', '0003_auto_20201007_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.CharField(default='N/A', max_length=10)),
                ('nombreCliente', models.CharField(default='N/A', max_length=200)),
                ('apellidoCliente', models.CharField(default='N/A', max_length=50)),
                ('numeroCelular', models.IntegerField(default=10)),
                ('direccion', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.CharField(default='N/A', max_length=100)),
                ('nombre', models.CharField(default='N/A', max_length=100)),
                ('tipoproducto', models.CharField(default='N/A', max_length=100)),
                ('precio', models.CharField(default='N/A', max_length=100)),
                ('totalcantidad', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProveedor', models.CharField(default='N/A', max_length=100)),
                ('nombreProveedor', models.CharField(default='N/A', max_length=200)),
                ('apellidoProveedor', models.CharField(default='N/A', max_length=200)),
                ('numeroCelular', models.IntegerField(default=10)),
                ('direccion', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='paralelo',
            name='carrera',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Paralelo',
        ),
    ]
